---
- name: Reboot all VyOS boxes
  hosts: vyos

  tasks:
    - name: Bounce VyOS VMs
      vyos_command:
        commands:
          - reboot now

    - name: Wait for Reconnect
      wait_for_connection:
        delay: 30
        timeout: 240

